### ISSUE TITLE
NeumorphicAppBar causing:  The getter 'current' was called on null.

### ISSUE THREAD

**Issue by havocy28** [Idean/Flutter-Neumorphic#171]
I'm trying to use the NeumorphicAppBar using Flutter-Neumorphic 3.02

The line causing the error is when building a Scaffold and the line:
appBar: NeumorphicAppBar()

I saw a reference for buttons and this requiring it to be wrapped in a theme, but could not find any examples.

Here is the stacktrace:

I/flutter ( 9324): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9324): The following NoSuchMethodError was thrown building NeumorphicAppBar(dirty, dependencies:
I/flutter ( 9324): [_InheritedTheme, _LocalizationsScope-[GlobalKey#4b8a8], _ModalScopeStatus], state:
I/flutter ( 9324): NeumorphicAppBarState#16011):
I/flutter ( 9324): The getter 'current' was called on null.
I/flutter ( 9324): Receiver: null
I/flutter ( 9324): Tried calling: current
I/flutter ( 9324):
I/flutter ( 9324): The relevant error-causing widget was:
[38;5;248mI/flutter ( 9324):   NeumorphicAppBar[39;49m
I/flutter ( 9324):
I/flutter ( 9324): When the exception was thrown, this was the stack:
[38;5;244mI/flutter ( 9324): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;248mI/flutter ( 9324): #1      NeumorphicAppBarState.build[39;49m
[38;5;244mI/flutter ( 9324): #2      StatefulElement.build[39;49m
[38;5;244mI/flutter ( 9324): #3      ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #4      StatefulElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #5      Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #6      StatefulElement.update[39;49m
[38;5;244mI/flutter ( 9324): #7      Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #8      ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #9      Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #10     ProxyElement.update[39;49m
[38;5;244mI/flutter ( 9324): #11     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #12     SingleChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter ( 9324): #13     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #14     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #15     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #16     ProxyElement.update[39;49m
[38;5;244mI/flutter ( 9324): #17     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #18     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #19     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #20     ProxyElement.update[39;49m
[38;5;244mI/flutter ( 9324): #21     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #22     RenderObjectElement.updateChildren[39;49m
[38;5;244mI/flutter ( 9324): #23     MultiChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter ( 9324): #24     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #25     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #26     StatefulElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #27     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #28     StatefulElement.update[39;49m
[38;5;244mI/flutter ( 9324): #29     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #30     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #31     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #32     ProxyElement.update[39;49m
[38;5;244mI/flutter ( 9324): #33     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #34     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #35     StatefulElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #36     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #37     StatefulElement.update[39;49m
[38;5;244mI/flutter ( 9324): #38     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #39     SingleChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter ( 9324): #40     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #41     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #42     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #43     StatelessElement.update[39;49m
[38;5;244mI/flutter ( 9324): #44     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #45     SingleChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter ( 9324): #46     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #47     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #48     StatefulElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #49     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #50     StatefulElement.update[39;49m
[38;5;244mI/flutter ( 9324): #51     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #52     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #53     StatefulElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #54     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #55     StatefulElement.update[39;49m
[38;5;244mI/flutter ( 9324): #56     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #57     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #58     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #59     ProxyElement.update[39;49m
[38;5;244mI/flutter ( 9324): #60     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #61     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #62     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #63     ProxyElement.update[39;49m
[38;5;244mI/flutter ( 9324): #64     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #65     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #66     StatefulElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #67     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #68     StatefulElement.update[39;49m
[38;5;244mI/flutter ( 9324): #69     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #70     RenderObjectElement.updateChildren[39;49m
[38;5;244mI/flutter ( 9324): #71     MultiChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter ( 9324): #72     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #73     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #74     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #75     StatelessElement.update[39;49m
[38;5;244mI/flutter ( 9324): #76     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #77     SingleChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter ( 9324): #78     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #79     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #80     StatefulElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #81     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #82     StatefulElement.update[39;49m
[38;5;244mI/flutter ( 9324): #83     Element.updateChild[39;49m
[38;5;244mI/flutter ( 9324): #84     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #85     StatefulElement.performRebuild[39;49m
[38;5;244mI/flutter ( 9324): #86     Element.rebuild[39;49m
[38;5;244mI/flutter ( 9324): #87     BuildOwner.buildScope[39;49m
[38;5;244mI/flutter ( 9324): #88     WidgetsBinding.drawFrame[39;49m
[38;5;244mI/flutter ( 9324): #89     RendererBinding._handlePersistentFrameCallback[39;49m
[38;5;244mI/flutter ( 9324): #90     SchedulerBinding._invokeFrameCallback[39;49m
[38;5;244mI/flutter ( 9324): #91     SchedulerBinding.handleDrawFrame[39;49m
[38;5;244mI/flutter ( 9324): #92     SchedulerBinding._handleDrawFrame[39;49m
[38;5;244mI/flutter ( 9324): #96     _invoke  (dart:ui/hooks.dart:253:10)[39;49m
[38;5;244mI/flutter ( 9324): #97     _drawFrame  (dart:ui/hooks.dart:211:3)[39;49m
I/flutter ( 9324): (elided 3 frames from dart:async)
I/flutter ( 9324):
I/flutter ( 9324): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/CrashlyticsPlugin( 9324): Unable to generate stack trace element from Dart side error.
I/flutter ( 9324): firebase_crashlytics: Error reported to Crashlytics.

**Comment by josiahsrc** [comment]
Duplicate of #169 I believe

**Comment by florent37** [comment]
is this fixed in 3.0.3 ?
